# Generated by Django 5.2.11 on 2026-02-21 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Central", "Central"),
                            ("Chimbu", "Chimbu"),
                            ("Eastern Highlands", "Eastern Highlands"),
                            ("East New Britain", "East New Britain"),
                            ("East Sepik", "East Sepik"),
                            ("Enga", "Enga"),
                            ("Gulf", "Gulf"),
                            ("Hela", "Hela"),
                            ("Jiwaka", "Jiwaka"),
                            ("Madang", "Madang"),
                            ("Manus", "Manus"),
                            ("Milne Bay", "Milne Bay"),
                            ("Morobe", "Morobe"),
                            ("New Ireland", "New Ireland"),
                            ("NCD (Port Moresby)", "NCD (Port Moresby)"),
                            ("Oro (Northern)", "Oro (Northern)"),
                            ("Sandaun (West Sepik)", "Sandaun (West Sepik)"),
                            ("Southern Highlands", "Southern Highlands"),
                            ("Western", "Western"),
                            ("Western Highlands", "Western Highlands"),
                            ("West New Britain", "West New Britain"),
                            ("Bougainville", "Bougainville"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "nationality",
                    models.CharField(default="Papua New Guinean", max_length=50),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        choices=[
                            ("grade_10", "Grade 10"),
                            ("grade_12", "Grade 12"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("degree", "Bachelor's Degree"),
                            ("postgraduate", "Postgraduate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("year_completed", models.PositiveIntegerField()),
                (
                    "grade_result",
                    models.CharField(
                        help_text="e.g. GPA 3.5/4.0, Credit, Distinction",
                        max_length=100,
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("current_employer", models.CharField(blank=True, max_length=200)),
                ("current_position", models.CharField(blank=True, max_length=200)),
                (
                    "work_history",
                    models.TextField(
                        blank=True, help_text="Briefly describe your work history"
                    ),
                ),
                ("reference1_name", models.CharField(max_length=100)),
                ("reference1_position", models.CharField(max_length=100)),
                ("reference1_phone", models.CharField(max_length=20)),
                ("reference2_name", models.CharField(blank=True, max_length=100)),
                ("reference2_position", models.CharField(blank=True, max_length=100)),
                ("reference2_phone", models.CharField(blank=True, max_length=20)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewed", "Interviewed"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("total_score", models.FloatField(blank=True, null=True)),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of application"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hr_notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("cv", "Curriculum Vitae (CV)"),
                            ("cover_letter", "Cover Letter"),
                            ("national_id", "National ID / Passport"),
                            ("birth_certificate", "Birth Certificate"),
                            ("academic_transcript", "Academic Transcript / Results"),
                            ("qualification", "Qualification / Certificate"),
                            ("reference_letter", "Reference Letter"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True, help_text="Extracted text from document (OCR)"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="recruitment.application",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("venue", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.application",
                    ),
                ),
                (
                    "panel_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interview_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("status_update", "Status Update"),
                            ("interview", "Interview"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("correctional_officer", "Correctional Officer"),
                            ("health", "Health & Medical"),
                            ("administration", "Administration"),
                            ("finance", "Finance & Accounts"),
                            ("engineering", "Engineering & Technical"),
                            ("legal", "Legal"),
                            ("security", "Security"),
                            ("it", "Information Technology"),
                            ("education", "Education & Training"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Central", "Central"),
                            ("Chimbu", "Chimbu"),
                            ("Eastern Highlands", "Eastern Highlands"),
                            ("East New Britain", "East New Britain"),
                            ("East Sepik", "East Sepik"),
                            ("Enga", "Enga"),
                            ("Gulf", "Gulf"),
                            ("Hela", "Hela"),
                            ("Jiwaka", "Jiwaka"),
                            ("Madang", "Madang"),
                            ("Manus", "Manus"),
                            ("Milne Bay", "Milne Bay"),
                            ("Morobe", "Morobe"),
                            ("New Ireland", "New Ireland"),
                            ("NCD (Port Moresby)", "NCD (Port Moresby)"),
                            ("Oro (Northern)", "Oro (Northern)"),
                            ("Sandaun (West Sepik)", "Sandaun (West Sepik)"),
                            ("Southern Highlands", "Southern Highlands"),
                            ("Western", "Western"),
                            ("Western Highlands", "Western Highlands"),
                            ("West New Britain", "West New Britain"),
                            ("Bougainville", "Bougainville"),
                            ("All", "All Provinces"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qualification_level",
                    models.CharField(
                        choices=[
                            ("grade_10", "Grade 10"),
                            ("grade_12", "Grade 12"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("degree", "Bachelor's Degree"),
                            ("postgraduate", "Postgraduate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("positions_available", models.PositiveIntegerField(default=1)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("min_age", models.PositiveIntegerField(default=18)),
                ("max_age", models.PositiveIntegerField(default=45)),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("open_date", models.DateField()),
                ("close_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "recipient_status",
                    models.CharField(
                        blank=True,
                        help_text="Target application status filter",
                        max_length=30,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recruitment.vacancy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.vacancy",
            ),
        ),
        migrations.CreateModel(
            name="InterviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(help_text="Score out of 100")),
                (
                    "communication_score",
                    models.FloatField(
                        default=0, help_text="Communication skills (out of 20)"
                    ),
                ),
                (
                    "knowledge_score",
                    models.FloatField(default=0, help_text="Job knowledge (out of 30)"),
                ),
                (
                    "attitude_score",
                    models.FloatField(
                        default=0, help_text="Attitude & professionalism (out of 25)"
                    ),
                ),
                (
                    "experience_score",
                    models.FloatField(
                        default=0, help_text="Relevant experience (out of 25)"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recommend", "Recommend"),
                            ("conditional", "Conditional Recommend"),
                            ("not_recommend", "Do Not Recommend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_scores",
                        to="recruitment.interview",
                    ),
                ),
                (
                    "panel_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("interview", "panel_member")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("vacancy", "applicant")},
        ),
    ]
