# Generated by Django 5.2.11 on 2026-02-21 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("applicant", "Applicant"),
                            ("hr_admin", "HR Administrator"),
                            ("panel_member", "Panel Member"),
                        ],
                        default="applicant",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Central", "Central"),
                            ("Chimbu", "Chimbu"),
                            ("Eastern Highlands", "Eastern Highlands"),
                            ("East New Britain", "East New Britain"),
                            ("East Sepik", "East Sepik"),
                            ("Enga", "Enga"),
                            ("Gulf", "Gulf"),
                            ("Hela", "Hela"),
                            ("Jiwaka", "Jiwaka"),
                            ("Madang", "Madang"),
                            ("Manus", "Manus"),
                            ("Milne Bay", "Milne Bay"),
                            ("Morobe", "Morobe"),
                            ("New Ireland", "New Ireland"),
                            ("NCD (Port Moresby)", "NCD (Port Moresby)"),
                            ("Oro (Northern)", "Oro (Northern)"),
                            ("Sandaun (West Sepik)", "Sandaun (West Sepik)"),
                            ("Southern Highlands", "Southern Highlands"),
                            ("Western", "Western"),
                            ("Western Highlands", "Western Highlands"),
                            ("West New Britain", "West New Britain"),
                            ("Bougainville", "Bougainville"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
